name: Release plugin files

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-subdir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update version number in .plugin file
        run: |
          version=${GITHUB_REF_NAME#v}
          sed -i "s|<Version>[0-9.]*</Version>|<Version>${version}</Version>|" RpFilter.plugin

      - name: Create zip file
        run: |
          (
            find . -name '*.lua' -type f;
            find Resources -type f;
            echo 'RpFilter.plugin'
          ) | zip -@ RP-Filter-${{ github.ref_name }}.zip

      - name: Upload zip file
        uses: softprops/action-gh-release@v2
        with:
          files: RP-Filter-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
